name: Get StreamLink Live
on:
  schedule:
    - cron: '0 0/1 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install Python
      run: |
        pip install bs4
        pip install pandas
        pip install openpyxl 
        pip install -U selenium
        python teste1.py
        $ libreoffice --convert-to pdf noticias.xlsx
        
        
                   
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
