name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  kodi-addon-submitter:
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:

    - name: Checkout
    - uses: actions/checkout@v2

    - name: Upload Addon zip to github release (krypton)
      id: upload-release-asset-krypton
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_name: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_content_type: application/zip

    - name: Upload Addon zip to github release (matrix)
      id: upload-release-asset-matrix
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.kodi-addon-submitter.outputs.addon-zip-matrix }}
        asset_name: ${{ steps.kodi-addon-submitter.outputs.addon-zip-matrix }}
        asset_content_type: application/zip
